config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#index'
  get 'contact', to: 'pages#contact'
  get 'about', to: 'pages#about'

  namespace :dashboard do
    root to: 'pages#index'
    resources :posts
    resources :users, only: :index
  end

  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_rich_text :content
  mount_uploader :thumbnail, ThumbnailUploader

  validates :title, presence: true
  validates :content, presence: true
  validates :user, presence: true
  validates :thumbnail, presence: true
  validates :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
  include Pundit
end

app/controllers/dashboard/base_controller.rb
module Dashboard
  class BaseController < ApplicationController
    before_action :authenticate_user!
    before_action :authenticate_admin!
    layout 'dashboard'

    private

    def authenticate_admin!
      redirect_to root_path, alert: 'The page you are looking for does not exist' unless current_user.admin?
    end

    def authorize(record, query = nil)
      super([:dashboard, record], query, policy_class: "#{controller_path.classify}Policy".constantize)
    end
  end
end

app/controllers/dashboard/pages_controller.rb
module Dashboard
  class PagesController < Dashboard::BaseController
    def index; end
  end
end

app/controllers/dashboard/posts_controller.rb
module Dashboard
  class PostsController < Dashboard::BaseController
    before_action :prepare_post, only: %i[edit update destroy]

    def index
      authorize Post

      @pagy, @posts = pagy(Post.all, items: 10)
    end

    def new
      @post = current_user.posts.new
    end

    def create
      @post = current_user.posts.new(post_params)

      if @post.save
        redirect_to dashboard_posts_path, notice: 'Post created succesfully'
      else
        render :new
      end
    end

    def edit; end

    def update
      if @post.update(post_params)
        redirect_to dashboard_posts_path, notice: 'Post updated succesfully'
      else
        render :edit
      end
    end

    def destroy
      if @post.destroy
        redirect_to dashboard_posts_path, notice: 'Post deleted succesfully'
      else
        redirect_to dashboard_posts_path, notice: 'Failure to delete post'
      end
    end

    private

    def post_params
      params.require(:post).permit(:title, :content, :user_id, :thumbnail, :description)
    end

    def prepare_post
      @post = Post.find(params[:id])
    end
  end
end

app/controllers/dashboard/users_controller.rb
module Dashboard
  class UsersController < Dashboard::BaseController
    def index
      authorize User

      @pagy, @users = pagy(User.all, items: 10)
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @pagy, @posts = pagy(Post.order(created_at: :desc), items: 5)

    respond_to do |format|
      format.html
      format.json do
        html = render_to_string(partial: 'posts/post', collection: @posts, as: :post, layout: false, formats: [:html])
        render json: { html: html, posts: @posts, next_page: @pagy.next, next_page_url: root_path(page: @pagy.next) }
      end
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :prepare_post, only: %i[show edit destroy update]

  def index
    authorize Post

    @pagy, @posts = pagy(
      current_user.posts.order(created_at: :desc), items: 5
    )
  end

  def new
    @post = current_user.posts.new

    authorize @post
  end

  def create
    @post = current_user.posts.new(post_params)
    authorize @post

    if @post.save
      redirect_to posts_path, notice: 'Post created succesfully'
    else
      render :new
    end
  end

  def show
    authorize @post
  end

  def edit
    authorize @post
  end

  def update
    authorize @post

    if @post.update(post_params)
      redirect_to posts_path, notice: 'Post updated succesfully'
    else
      render :edit
    end
  end

  def destroy
    authorize @post

    if @post.destroy
      redirect_to posts_path, notice: 'Post deleted succesfully'
    else
      redirect_to posts_path, notice: 'Failure to delete post'
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :user_id, :thumbnail, :description)
  end

  def prepare_post
    @post = Post.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/dashboard/pages/index.html.erb
<div class="container-fluid">
  <h1 class="mt-4">Dashboard index Page</h1>
</div>

app/views/dashboard/posts/_form.html.erb
<div class="row">
  <div class="col-md-12 mt-2">
    <%= render partial: "dashboard/shared/error_messages", locals: { resource: post } %>
    <%= form_for(post, url: url, class: "form form-horizontal") do |form| %>
      <div class="form-group">
        <%= form.label :title %>
        <%= form.text_field :title, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :description %>
        <%= form.text_area :description, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :content %>
        <%= form.rich_text_area :content %>
      </div>

      <div class="form-group">
        <%= form.file_field :thumbnail %>
      </div>
      <%- thumbnail_url = form.object.thumbnail.url || '' %>
      <%= image_tag thumbnail_url, class: 'w-100 mb-4 post_thumbnail_image', style: "max-width: 600px;" %>

      <div class="form-group">
        <%= form.submit "Save", class: "btn btn-success" %>
      </div>
    <% end %>
  </div>
</div>

app/views/dashboard/posts/edit.html.erb
<div class="p-5 container-fluid">
  <h3>Edit post</h3>
  <%= render partial: "form", locals: { post: @post, url: dashboard_post_path } %>
</div>

app/views/dashboard/posts/index.html.erb
<div class="p-5 container-fluid">
  <%= link_to 'Create post', new_dashboard_post_path, class: 'btn btn-primary mb-4' %>
  <h3>All posts</h3>
  <table class="table mt-4">
    <thead>
      <tr>
        <th>ID</th>
        <th>Title</th>
        <th>Description</th>
        <th>Author</th>
        <th>Created at</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @posts.each do |post| %>
        <tr>
          <td><%= post.id %></td>
          <td><%= post.title %></td>
          <td><%= post.description[0..20] %> ...</td>
          <td><%= post.user.email %></td>
          <td><%= post.created_at %></td>
          <td>
            <%= link_to "Edit", edit_dashboard_post_path(post), class: 'btn btn-sm btn-primary' %>
            <%= link_to "Delete", dashboard_post_path(post), class: 'btn btn-sm btn-danger', method: :delete, data: { confirm: 'Are you sure want to delete this ?' } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class="float-right">
    <%== pagy_bootstrap_nav(@pagy) %>
  </div>
</div>

app/views/dashboard/posts/new.html.erb
<div class="p-5 container-fluid">
  <h3>Add new post</h3>
  <%= render partial: "form", locals: { post: @post, url: dashboard_posts_path } %>
</div>

app/views/dashboard/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <strong>
        <%= "The form contains #{resource.errors.count} #{resource.errors.count > 1 ? 'error'.pluralize : 'error'}"  %>
      </strong>
      <ul>
          <% resource.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  </div>
<% end %>

app/views/dashboard/shared/_flash.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible fade show ml-5 mr-5 mt-4" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-danger alert-dismissible fade show ml-5 mr-5 mt-4" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/dashboard/users/index.html.erb
<div class="p-5 container-fluid">
  <h3>All userss</h3>
  <table class="table mt-4">
    <thead>
      <tr>
        <th>ID</th>
        <th>Email</th>
        <th>Role</th>
        <th>Total posts</th>
        <th>Joined at</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.id %></td>
          <td><%= user.email %></td>
          <td><%= user.admin? ? 'Admin' : 'Regular' %></td>
          <td><%= user.posts.count %></td>
          <td><%= user.created_at %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class="float-right">
    <%== pagy_bootstrap_nav(@pagy) %>
  </div>
</div>

app/views/layouts/_dashboard_footer.html.erb
<footer class="py-4 bg-light mt-auto">
  <div class="container-fluid">
      <div class="d-flex align-items-center justify-content-between small">
          <div class="text-muted">Copyright &copy; Your Website 2020</div>
          <div>
              <a href="#">Privacy Policy</a>
              &middot;
              <a href="#">Terms &amp; Conditions</a>
          </div>
      </div>
  </div>
</footer>

app/views/layouts/_dashboard_navbar.html.erb
<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
  <%= link_to "Ror-simple-blog", dashboard_root_path, class: "navbar-brand" %>
  <button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#"><i class="fas fa-bars"></i></button>
  <!-- Navbar Search-->
  <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
      <div class="input-group">
          <input class="form-control" type="text" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2" />
          <div class="input-group-append">
              <button class="btn btn-primary" type="button"><i class="fas fa-search"></i></button>
          </div>
      </div>
  </form>
  <!-- Navbar-->
  <ul class="navbar-nav ml-auto ml-md-0">
      <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i>&nbsp; <%= current_user.email %></a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
              <%= link_to "Back to home", root_path, class: 'dropdown-item' %>
              <div class="dropdown-divider"></div>
              <%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
          </div>
      </li>
  </ul>
</nav>

app/views/layouts/_dashboard_sidenav.html.erb
<div id="layoutSidenav_nav">
  <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
      <div class="sb-sidenav-menu">
          <div class="nav">
              <div class="sb-sidenav-menu-heading">Core</div>
                <%= link_to dashboard_root_path, class: "nav-link" do %>
                  <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                  Dashboard
                <% end %>
              <div class="sb-sidenav-menu-heading">Module</div>
              <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePosts" aria-expanded="false" aria-controls="collapsePosts">
                  <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                  Post
                  <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
              </a>
              <div class="collapse" id="collapsePosts" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
                <nav class="sb-sidenav-menu-nested nav">
                  <%= link_to "Management", dashboard_posts_path, class: "nav-link" %>
                  <%= link_to "Create", new_dashboard_post_path, class: "nav-link" %>
                </nav>
              </div>

              <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUsers" aria-expanded="false" aria-controls="collapseUsers">
                  <div class="sb-nav-link-icon"><i class="fas fa-users"></i></div>
                  User
                  <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
              </a>
              <div class="collapse" id="collapseUsers" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
                <nav class="sb-sidenav-menu-nested nav">
                  <%= link_to "Management", dashboard_users_path, class: "nav-link" %>
                </nav>
              </div>
          </div>
      </div>
      <div class="sb-sidenav-footer">
          <div class="small">Logged in as:</div>
          <%= current_user.email %>
      </div>
  </nav>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <ul class="list-inline text-center">
          <li class="list-inline-item">
            <a href="#">
              <span class="fa-stack fa-lg">
                <i class="fas fa-circle fa-stack-2x"></i>
                <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
              </span>
            </a>
          </li>
          <li class="list-inline-item">
            <a href="#">
              <span class="fa-stack fa-lg">
                <i class="fas fa-circle fa-stack-2x"></i>
                <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
              </span>
            </a>
          </li>
          <li class="list-inline-item">
            <a href="#">
              <span class="fa-stack fa-lg">
                <i class="fas fa-circle fa-stack-2x"></i>
                <i class="fab fa-github fa-stack-1x fa-inverse"></i>
              </span>
            </a>
          </li>
        </ul>
        <p class="copyright text-muted">Copyright &copy; Your Website 2020</p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="masthead" style="background-image: url(' <%= bg_image %>')">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="site-heading">
          <h1>Clean Blog</h1>
          <span class="subheading">A Blog Theme by Start Bootstrap</span>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
  <div class="container">
    <%= link_to "Ror-simple-blog", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      Menu
      <i class="fas fa-bars"></i>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <%= link_to "home", root_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "about", about_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "contact", contact_path, class: 'nav-link' %>
        </li>
        <% if current_user.present? %>
          <li class="nav-item dropdown">
            <a class="nav-item nav-link dropdown-toggle mr-md-2" href="#" id="user-actions" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= current_user.email %>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="user-actions">
              <%= link_to "Manage posts", posts_path, class: 'dropdown-item' %>
              <%= link_to "Create new post", new_post_path, class: 'dropdown-item' %>
              <%= link_to "Change password", edit_user_registration_path, class: 'dropdown-item' %>
              <hr>
              <% if current_user.admin? %>
                <%= link_to "Dashboard", dashboard_root_path, class: 'dropdown-item' %>
              <% end %>
              <%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Register", new_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RorSimpleBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render "shared/flash" %>
    <%= render "layouts/navbar" %>
    <%= yield %>
    <hr>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ror simple blog - Dashboard</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'dashboard/application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'dashboard/application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/dashboard_navbar" %>
    <div id="layoutSidenav">
      <%= render "layouts/dashboard_sidenav" %>
      <div id="layoutSidenav_content">
        <main>
          <%= render "dashboard/shared/flash" %>
          <%= yield %>
        </main>
        <%= render "layouts/dashboard_footer" %>
      </div>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<%= render partial: "layouts/header", locals: { bg_image: asset_pack_url('media/images/about-bg.jpg') }%>
<div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur voluptates odit, fuga atque ea nobis sit soluta odio, adipisci quas excepturi maxime quae totam ducimus consectetur?</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius praesentium recusandae illo eaque architecto error, repellendus iusto reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum in officia voluptas voluptatibus, minus!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut consequuntur magnam, excepturi aliquid ex itaque esse est vero natus quae optio aperiam soluta voluptatibus corporis atque iste neque sit tempora!</p>
      </div>
    </div>
  </div>

app/views/pages/contact.html.erb
<%= render partial: "layouts/header", locals: { bg_image: asset_pack_url('media/images/contact-bg.jpg') }%>
<div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <p>Want to get in touch? Fill out the form below to send me a message and I will get back to you as soon as possible!</p>
        <!-- Contact Form - Enter your email address on line 19 of the mail/contact_me.php file to make this form work. -->
        <!-- WARNING: Some web hosts do not allow emails to be sent through forms to common mail hosts like Gmail or Yahoo. It's recommended that you use a private domain email address! -->
        <!-- To use the contact form, your site must be on a live web host with PHP! The form will not work locally! -->
        <form name="sentMessage" id="contactForm" novalidate>
          <div class="control-group">
            <div class="form-group floating-label-form-group controls">
              <label>Name</label>
              <input type="text" class="form-control" placeholder="Name" id="name" required data-validation-required-message="Please enter your name.">
              <p class="help-block text-danger"></p>
            </div>
          </div>
          <div class="control-group">
            <div class="form-group floating-label-form-group controls">
              <label>Email Address</label>
              <input type="email" class="form-control" placeholder="Email Address" id="email" required data-validation-required-message="Please enter your email address.">
              <p class="help-block text-danger"></p>
            </div>
          </div>
          <div class="control-group">
            <div class="form-group col-xs-12 floating-label-form-group controls">
              <label>Phone Number</label>
              <input type="tel" class="form-control" placeholder="Phone Number" id="phone" required data-validation-required-message="Please enter your phone number.">
              <p class="help-block text-danger"></p>
            </div>
          </div>
          <div class="control-group">
            <div class="form-group floating-label-form-group controls">
              <label>Message</label>
              <textarea rows="5" class="form-control" placeholder="Message" id="message" required data-validation-required-message="Please enter a message."></textarea>
              <p class="help-block text-danger"></p>
            </div>
          </div>
          <br>
          <div id="success"></div>
          <button type="submit" class="btn btn-primary" id="sendMessageButton">Send</button>
        </form>
      </div>
    </div>
  </div>

app/views/pages/index.html.erb
<%= render partial: "layouts/header", locals: { bg_image: asset_pack_url('media/images/home-bg.jpg') }%>
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
      <h3 class="mb-5">All posts</h3>
      <div class="post-list">
        <%= render partial: "posts/post", collection: @posts, as: :post %>
      </div>
      <%= link_to "Older posts", root_path(page: 2), class: 'btn btn-primary float-right load-more' %>
    </div>
  </div>
</div>

app/views/posts/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
      <%= render "devise/shared/error_messages", resource: post %>
      <%= form_for(post) do |f| %>
        <div class="control-group">
          <div class="form-group floating-label-form-group controls mb-4">
            <h4>Title</h4>
            <%= f.label :title %><br />
            <%= f.text_field :title, autofocus: true, placeholder: "Title...", class: "form-control" %>
            <p class="help-block text-danger"></p>
          </div>
        </div>

        <div class="control-group">
          <div class="form-group floating-label-form-group controls mb-4">
            <h4>Description</h4>
            <%= f.label :description %><br />
            <%= f.text_field :description, autofocus: true, placeholder: "description...", class: "form-control" %>
            <p class="help-block text-danger"></p>
          </div>
        </div>

        <div class="control-group">
          <div class="form-group floating-label-form-group controls mb-4">
            <h4>Content</h4>
            <%= f.label :content %><br />
            <%= f.rich_text_area :content, autofocus: true, placeholder: "content..." %>
            <p class="help-block text-danger"></p>
          </div>
        </div>

        <div class="control-group">
          <div class="form-group floating-label-form-group controls mb-4">
            <h4>Thumbnail</h4>
            <%= f.file_field :thumbnail %>
          </div>

          <%- thumbnail_url = f.object.thumbnail.url || '' %>
          <%= image_tag thumbnail_url, class: 'w-100 mb-4 post_thumbnail_image' %>
        </div>

        <%= f.submit "Submit", class: "col-md-12 btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/_post.html.erb
<div class="post-preview-wrapper d-flex mb-5">
  <div class="post-preview-thumbnail">
    <%= image_tag post.thumbnail.url, class: 'post-preview-thumbnail-image' %>
  </div>
  <div class="post-preview pl-4 pr-4">
    <%= link_to post_path(post) do %>
      <h2 class="post-title">
        <%= post.title %>
      </h2>
    <% end %>
    <p class="post-meta">Posted by
      <strong><%= post.user&.email %></strong>
      on <%= post.created_at.strftime("%B, %d, %Y") %>
    </p>
  </div>
</div>

app/views/posts/edit.html.erb
<header class="masthead">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="post-heading">
          <h1>Edit post</h1>
          <br>
        </div>
      </div>
    </div>
  </div>
</header>

<article>
  <%= render partial: "posts/form", locals: { post: @post } %>
</article>

app/views/posts/index.html.erb
<%= render partial: "layouts/header", locals: { bg_image: asset_pack_url('media/images/home-bg.jpg') }%>
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
      <div class="d-flex justify-content-between">
        <h3 class="mb-5">Manage your posts</h3>
        <div>
          <%= link_to "New post", new_post_path, class: 'btn btn-primary btn-sm' %>
        </div>
      </div>
      <% if @posts.blank?  %>
        <p>Empty data</p>
      <% end %>

      <%= render partial: "post", collection: @posts, as: :post %>

      <div class="float-right">
        <% if @posts.present?  %>
          <%== pagy_bootstrap_nav(@pagy) %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<header class="masthead">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="post-heading">
          <h1>Create a new post</h1>
          <br>
        </div>
      </div>
    </div>
  </div>
</header>

<article>
  <%= render partial: "posts/form", locals: { post: @post } %>
</article>

app/views/posts/show.html.erb
<header class="masthead" style="background-image: url('<%= @post.thumbnail %>'">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="post-heading">
          <h1><%= @post.title %></h1>
          <h2 class="subheading"><%= @post.description %></h2>
          <span class="meta">Posted by
            <a href="#"><%= @post.user&.email %></a>
            on <%= %>
          </span>
          <br>
          <% if policy(@post).edit? %>
            <%= link_to "Edit", edit_post_path(@post), class: "btn btn-primary btn-sm" %>
          <% end %>

          <% if policy(@post).destroy? %>
            <%= link_to "Delete", post_path(@post), method: :delete, class: "btn btn-danger btn-sm", data: { confirm: 'Are you sure want to delete this post ?' } %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</header>

<article>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <%= raw @post.content %>
      </div>
    </div>
  </div>
</article>